set -g default-terminal "xterm-256color"
set-option -g repeat-time 0
set-option -g history-limit 50000
set-window-option -g mode-keys vi

# Clipboard
set -s set-clipboard external

# Periodically set pane names
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Keep same directory when creating new window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Quick reload
bind R source-file ~/.tmux.conf \; display "Reloaded tmux.conf"

# tmux power
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'

set -g @dracula-plugins "git time"
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-border-contrast true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.tmux/plugins/tpm/tpm'
